"""empty message

Revision ID: 919ab10895d4
Revises: c8c0c4fa1abb
Create Date: 2023-04-23 20:27:40.821212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919ab10895d4'
down_revision = 'c8c0c4fa1abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
