"""empty message

Revision ID: c8f0a03f121c
Revises: 919ab10895d4
Create Date: 2023-04-25 10:35:42.871123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f0a03f121c'
down_revision = '919ab10895d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_cart_id_fkey', type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('orders_qties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('orders_qties_cart_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_qties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_qties_cart_id_fkey', 'carts', ['cart_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_cart_id_fkey', 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###
