"""empty message

Revision ID: e12c9e309f51
Revises: c8f0a03f121c
Create Date: 2023-04-25 13:13:53.236163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12c9e309f51'
down_revision = 'c8f0a03f121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_qties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_qties', schema=None) as batch_op:
        batch_op.drop_column('prize')

    # ### end Alembic commands ###
